apiVersion: v1
kind: Service
metadata:
  name: kiwicom-summercamp-entry-task-service
spec:
  type: LoadBalancer
  selector:
    pod: kiwicom-summercamp-entry-task
  ports:
    - name: http
      protocol: TCP
      port: 50000
      targetPort: 3000
